name: Nuget

on: 
  workflow_dispatch:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Package 
      run: dotnet pack -c Release --no-build --property:PackageOutputPath=../acpkg
    - name: Push to Nuget
      run: dotnet nuget push "./acpkg/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_PUBLISH_KEY }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: 'true'
        makeLatest: 'true'